# Reusable step: Publish npm package from .tgz artifact
parameters:
    - name: tgzPath
      type: string
    - name: npmPublishTag
      type: string
      default: 'latest'
    - name: npmPublishDryRun
      type: boolean
      default: false

steps:
    - script: mv *.tgz package.tgz
      displayName: 'Rename tgz file'
      workingDirectory: '${{ parameters.tgzPath }}'
    - task: Npm@1
      displayName: 'npm publish'
      inputs:
          command: custom
          workingDir: '${{ parameters.tgzPath }}'
          verbose: true
          customCommand: 'publish package.tgz --tag ${{ parameters.npmPublishTag }} --dry-run ${{ lower(parameters.npmPublishDryRun) }}'
          customEndpoint: terraform-mcp-server-npm
