jobs:
    - job: Build
      pool:
          type: linux
      variables:
          ob_outputDirectory: '$(Build.ArtifactStagingDirectory)/out'
          ob_git_checkout: true
      steps:
          - template: /azure-pipelines/templates/steps/setup-node.yml@self
            parameters:
                nodeVersion: '20.x'
          - script: npm audit --production
            displayName: 'Run vulnerability scan'
          - script: npm run build
            displayName: 'npm run build'
          - task: CopyFiles@2
            displayName: 'Copy files to staging'
            inputs:
                sourceFolder: '$(Build.SourcesDirectory)'
                contents: |
                    dist/**
                    LICENSE
                    package.json
                    README.md
                targetFolder: '$(Build.ArtifactStagingDirectory)/dropInput'
                cleanTargetFolder: true
          - script: npm prune --production
            displayName: 'npm prune --production'
          - script: npm pack
            displayName: 'npm pack'
            workingDirectory: '$(Build.ArtifactStagingDirectory)/dropInput'
          - script: mv $(Build.ArtifactStagingDirectory)/dropInput/*.tgz $(ob_outputDirectory)/
            displayName: 'Move package to output directory'
